### ISSUE TITLE
Dead URL in README

### ISSUE THREAD

**Issue by rywhale** [CSHS-CWRA/CSHShydRology#9]
Found this dead link while taking a look through the package to find areas I can clean up/contribute. 

The link to the CSHS page at the end of the "What is CSHS Hydrology?" section of the README 404s. 

Link is currently http://www.cwra.org/en/branches/affiliates/cshs-a

Would submit a PR but not sure where this link should actually point. 

### **Link location in README:**
![image](https://user-images.githubusercontent.com/33959166/49663945-4e095f00-fa1e-11e8-8992-0ff02963dd59.png)

### **Resulting 404:**
![image](https://user-images.githubusercontent.com/33959166/49663959-5bbee480-fa1e-11e8-9e6b-79f13d201990.png)

**Comment by KevinShook** [comment]
Thanks - I don't know either, but will look into it.
K

**Comment by KevinShook** [comment]
Just went checked the website. Looks like it should actually be
https://cwra.org/en/affiliates-programs/cshs/
I'll fix it.

**Comment by KevinShook** [comment]
Fixed - the link now points to the correct URL
